angular.module('api.config', [])
    .constant('YLC_API','https://ylc-api.herokuapp.com/')
    .constant('Yumigo_API','https://yumigo.herokuapp.com/')
    // .constant('Yumigo_API','http://localhost:3030/')
    // .constant('YLC_API','http://localhost:3000/')